# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  armDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      # - name: Deploy Resource Group rg-githubactions with AZ CLI
      #   uses: Azure/cli@v2.0.0
      #   with:
      #     inlinescript: |
      #       az deployment sub create --location "UK South" --template-file ./arm-templates/resource-group.json
      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: 1e68b0b5-57b5-4a9f-8746-cb26c640cbca
          region: UK South
          template: ./arm-templates/resource-group.json
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId: 1e68b0b5-57b5-4a9f-8746-cb26c640cbca
          template: ./arm-templates/storage-account.json
          parameters: 
            ./arm-templates/storage-account.parameters.json
            storageAccountName=iacf8nl002
            location="UK West"
          deploymentMode: incremental
  